### ISSUE TITLE
数据来源

### ISSUE THREAD

**Issue by smartwalle** [moolighty/geo#1]
你好，我最近也在整理这方面的数据，但是一直没有找到一分比较全面的，我想请问一下，你这些数据是从哪里来的呢？

**Comment by jyxjjj** [comment]
> 你好，我最近也在整理这方面的数据，但是一直没有找到一分比较全面的，我想请问一下，你这些数据是从哪里来的呢？

C:/Program Files(x86)/Tencent/QQ/I18N/2052/LocList.xml
C:/Program Files(x86)/Tencent/QQInternational/I18N/1033/LocList.xml
